### PR TITLE
[Enhance] ipynb badges

### PR DESCRIPTION
**Pull request by shiv248**
refer to #6
pulling out file refac, adding badges

would possibly need to host badges, otherwise more PR #1 issues will happen of badges not loading due to browser or ipynb viewer limitations

### CODE REVIEW

**Review by rlancemartin — COMMENTED** [review]
this is great. 

apparently we need to host the page. 

can you include link to the image? 

cc: @jessicaou

**Comment by shiv248** [comment]
would need to host the svg image. currently sometimes due to limitations of GH/ipynb viewers they don't load the entire base64 as we can see in this PR's blob [here](https://github.com/langchain-ai/langchain-academy/blob/38af6c3f2771f43d00328b44041e6ea7e2506667/module-0/basics.ipynb).


image

but if we host it externally and then link it for example using url `https://github.com/user-attachments/assets/fe8596de-1e68-4eb3-b730-eaa045138dc8` (this url is possibly temp, I don't know the mechanics of `github.com/user-attatchments`) [Open in LangChain Academy](https://academy.langchain.com/courses/take/intro-to-langgraph/lessons/58239417-lesson-7-agent-with-memory)

image
we can see that it took that img host and rendered it in GH ipynb successfully, [here](https://github.com/shiv248/langchain-academy/blob/badges-links-fix/module-0/basics.ipynb)

I can forward the svgs to @jessicaou on slack.

**Comment by jessicaou** [comment]
Can we use this link: https://cdn.prod.website-files.com/65b8cd72835ceeacd4449a53/66e8801d1313b74d189c69af_lcacademybutton.png

**Comment by shiv248** [comment]
@jessicaou I tried the image you linked as shown below, I'm not sure if that is the desired output. but to me to looks off next to `Open in Colab`, would need to adjust the dimensions.
Recording 2024-09-16 at 13 27 16

**Comment by jessicaou** [comment]
New links for SVGs here, let me know if this works :)
https://cdn.prod.website-files.com/65b8cd72835ceeacd4449a53/66e9eba12c7b7688aa3dbb5e_LCA-badge-green.svg

https://cdn.prod.website-files.com/65b8cd72835ceeacd4449a53/66e9eba1020525eea7873f96_LCA-big-green%20(2).svg

**Comment by rlancemartin** [comment]
Good! @shiv248 I can merge unless you have any more changes you want to get in?

**Comment by shiv248** [comment]
for this issue and pr, looks good to me.

**Pull request merged**
